# Основные параметры конфигурации: N, M, K - лимиты по достижению которых, сервис считает попытку брутфорсом.
# не более N = 10 попыток в минуту для данного логина.
# не более M = 100 попыток в минуту для данного пароля (защита от обратного brute-force).
# не более K = 1000 попыток в минуту для данного IP (число большое, т.к. NAT).

app:
  mode: 'Development'
  loginLimit: 10
  passLimit: 100
  ipLimit: 1000

server:
  port: :50051
  mode: development
  readTimeout: 5
  writeTimeout: 5
  ctxDefaultTimeout: 12
  debug: false

logger:
  development: true
  level: info

postgres:
  dsn: 'postgres://postgres:passpass@postgres:5432/postgres?sslmode=disable'
  pool_max: 2

