version: "3.9"

services:
  antibruteforce:
    container_name: antibruteforce
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '50051:50051'
    networks:
      - default

networks:
  default:
    driver: bridge