# Основные параметры конфигурации: N, M, K - лимиты по достижению которых, сервис считает попытку брутфорсом.
# не более N = 10 попыток в минуту для данного логина.
# не более M = 100 попыток в минуту для данного пароля (защита от обратного brute-force).
# не более K = 1000 попыток в минуту для данного IP (число большое, т.к. NAT).

app:
  mode: 'Development'
  loginLimit: 10
  passLimit: 100
  ipLimit: 1000

server:
  port: :50051
  mode: development
  jwtSecretKey: secretkey
  readTimeout: 5
  writeTimeout: 5
  ssl: true
  ctxDefaultTimeout: 12
  debug: false

logger:
  development: true
  level: info

postgres:
  dsn: 'postgres://postgres:passpass@localhost:5432/abfdb'
  pool_max: 2


#  dsn: 'postgres://abf:passpass@localhost:5432/abfdb'
#
#'pgsql:host=localhost;port=5432;dbname=testdb;user=bruce;password=mypass'