# Основные параметры конфигурации: N, M, K - лимиты по достижению которых, сервис считает попытку брутфорсом.
# не более N = 10 попыток в минуту для данного логина.
# не более M = 100 попыток в минуту для данного пароля (защита от обратного brute-force).
# не более K = 1000 попыток в минуту для данного IP (число большое, т.к. NAT).

app:
  mode: 'Development'
  loginLimit: 1
  passLimit: 2
  ipLimit: 3

server:
  port: :50051
  pprofPort: :5555
  mode: Development
  jwtSecretKey: secretkey
  cookieName: jwt-token
  readTimeout: 5
  writeTimeout: 5
  ssl: true
  ctxDefaultTimeout: 12
  csrf: true
  debug: false
  maxConnectionIdle: 5
  timeout: 15
  maxConnectionAge: 5
  time: 5

logger:
  development: true
  level: info

postgres:
  dsn: 'postgres://postgres:passpass@localhost:5432/abfdb'
  pool_max: 2


#  dsn: 'postgres://abf:passpass@localhost:5432/abfdb'
#
#'pgsql:host=localhost;port=5432;dbname=testdb;user=bruce;password=mypass'