# Основные параметры конфигурации: N, M, K - лимиты по достижению которых, сервис считает попытку брутфорсом.
# не более N = 10 попыток в минуту для данного логина.
# не более M = 100 попыток в минуту для данного пароля (защита от обратного brute-force).
# не более K = 1000 попыток в минуту для данного IP (число большое, т.к. NAT).
